[package]
authors = [
  "Hunar Roop Kahlon <hunar.roop@gmail.com>"
]
description = "A minecraft data and resource pack language."
edition = "2021"
name = "mcl"
version = "0.0.0"

[dependencies]
uuid = { version = "1.3.0", features = ["v4"] }

